version: '3'
services:
  nextapp:
    environment:
      - APP_NAME=app # ここを変えた場合.devcontainer.jsonのeslintの設定を変えなければならない
    container_name: nextapp
    build:
      context: .
      dockerfile: next_dev/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      - ~/.ssh:/home/node/.ssh
    tty: true